export { StoryNormalList } from './story-normal-list';
export { StoryCircularList } from './story-circular-list';
export { StoryRectList } from './story-rect-list';
export { StoryArrowList } from './story-arrow-list';
export { StoryThinArrowList } from './story-thin-arrow-list';
export { StoryVerticalShapeClipList } from './story-vertical-shape-clip-list';
export { IconLabelComponent } from './icon-label-component';
export type { IStoryListAttrs, ILiItemAttrs, IStoryArrowListAttrs, IStoryShapeListAttrs } from './type';
export type { IIconLabelComponentAttrs } from './icon-label-component';
export { loadStoryListComponent } from './register';
