core:
  - changed-files:
      - any-glob-to-any-file: 'packages/vrender/**'

react:
  - changed-files:
      - any-glob-to-any-file: 'packages/react-vrender/**'

react-utils:
  - changed-files:
      - any-glob-to-any-file: 'packages/react-vrender-utils/**'

components:
  - changed-files:
      - any-glob-to-any-file: 'packages/vrender-components/**'

kits:
  - changed-files:
      - any-glob-to-any-file: 'packages/vrender-kits/**'

test:
  - changed-files:
      - any-glob-to-any-file: 'packages/*/__tests__/*'

docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'

eslint:
  - changed-files:
      - any-glob-to-any-file:
          - 'share/eslint-config/**'
          - 'packages/*/.eslintrc.js'

jest:
  - changed-files:
      - any-glob-to-any-file:
          - 'share/jest-config/**'
          - 'packages/*/jest.config.js'

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - 'share/ts-config/**'
          - 'packages/*/tsconfig.json'
          - 'packages/*/tsconfig.eslint.json'

bundler:
  - changed-files:
      - any-glob-to-any-file:
          - 'tools/bundler/**'
          - 'packages/*/bundler.config.js'

chore:
  - changed-files:
      - any-glob-to-any-file:
          - 'common/autoinstallers/**'
          - 'common/git-hooks/**'
          - 'common/scripts/**'
