import { genNumberType } from './tools';

export const ARC_NUMBER_TYPE = genNumberType();
export const ARC3D_NUMBER_TYPE = genNumberType();
export const AREA_NUMBER_TYPE = genNumberType();
export const CIRCLE_NUMBER_TYPE = genNumberType();
export const GLYPH_NUMBER_TYPE = genNumberType();
export const GROUP_NUMBER_TYPE = genNumberType();
export const IMAGE_NUMBER_TYPE = genNumberType();
export const LINE_NUMBER_TYPE = genNumberType();
export const PATH_NUMBER_TYPE = genNumberType();
export const POLYGON_NUMBER_TYPE = genNumberType();
export const PYRAMID3D_NUMBER_TYPE = genNumberType();
export const RECT_NUMBER_TYPE = genNumberType();
export const RECT3D_NUMBER_TYPE = genNumberType();
export const RICHTEXT_NUMBER_TYPE = genNumberType();
export const SYMBOL_NUMBER_TYPE = genNumberType();
export const TEXT_NUMBER_TYPE = genNumberType();

export const GraphicService = Symbol.for('GraphicService');
export const GraphicCreator = Symbol.for('GraphicCreator');

export const VArea = 'area';
export const VCircle = 'circle';
export const VEllipse = 'ellipse';
export const VLine = 'line';
export const VRect = 'rect';
export const VRect3d = 'rect3d';
export const VPath = 'path';
export const VRichText = 'richtext';
export const VText = 'text';
export const VArc = 'arc';
export const VArc3d = 'arc3d';
export const VImage = 'image';
export const VSymbol = 'symbol';
export const VGroup = 'group';
export const VShadowRoot = 'shadowroot';
export const VPolygon = 'polygon';
export const VPyramid3d = 'pyramid3d';
export const VGlyph = 'glyph';
