name: Check of pull request

# 这里业务方根据需求设置
on:
  pull_request:
    branches: ['develop', 'dev/**']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: './common/config/rush/pnpm-lock.yaml'

      - uses: xile611/pr-type-check@main
        with:
          pull_request_body: |
            ${{ github.event.pull_request.body }}
          pull_request_head: ${{ github.event.pull_request.head.ref }}
